name: Deploy to prod
on: push
concurrency:
  group: "actiontests-prod"
jobs:
  tag:
    name: Tag the release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Message'
        id: 'changelog-ci'
        run: |
          git log --oneline > abc.log
          MY_STRING=$(cat abc.log)
          echo "MY_STRING<<EOF" >> $GITHUB_ENV
          echo "$MY_STRING" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: display string
        run: |
          echo "The string is: ${{ env.MY_STRING }}"
          
      - name: Get Changelog Output
        run: |
          echo "${{ env.MY_STRING }}" >> $GITHUB_STEP_SUMMARY

  # slack:
  #   runs-on: ubuntu-latest
  #   if: ${{ always() }}
  #   needs:
  #     - deploy-prod-live
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: notify
  #       uses: privacy-com/shared-github-actions/.github/actions/slack@main
  #       with:
  #         SERVICE: privacy-dashboard
  #         ENVIRONMENT: production
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PROD }}
  #         COLOR: ${{(!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')) && '#00FF00' || '#FF0000' }}
