name: Deploy to prod
on: push
concurrency:
  group: "actiontests-prod"
jobs:
  tag:
    name: Tag the release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Get Message'
      - run: |
          cat 'commit_message<<EOF' >> $GITHUB_OUTPUT
          echo "$(git log --oneline)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      
  # slack:
  #   runs-on: ubuntu-latest
  #   if: ${{ always() }}
  #   needs:
  #     - deploy-prod-live
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: notify
  #       uses: privacy-com/shared-github-actions/.github/actions/slack@main
  #       with:
  #         SERVICE: privacy-dashboard
  #         ENVIRONMENT: production
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PROD }}
  #         COLOR: ${{(!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')) && '#00FF00' || '#FF0000' }}
