name: Deploy to prod
on: push
concurrency:
  group: "actiontests-prod"
jobs:
  tag:
    name: Tag the release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          curl https://example.com >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo $GITHUB_ENV
          echo $GITHUB_ENV > $GITHUB_STEP_SUMMARY

  # slack:
  #   runs-on: ubuntu-latest
  #   if: ${{ always() }}
  #   needs:
  #     - deploy-prod-live
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: notify
  #       uses: privacy-com/shared-github-actions/.github/actions/slack@main
  #       with:
  #         SERVICE: privacy-dashboard
  #         ENVIRONMENT: production
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PROD }}
  #         COLOR: ${{(!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')) && '#00FF00' || '#FF0000' }}
