name: Deploy to prod
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag the build'
        required: true
        type: string
concurrency:
  group: "actiontests-prod"
jobs:
  tag-the-release:
    name: Tag the release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag the release
        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a ${{ inputs.tag }} -m "Tagging the release ${{ inputs.tag }}"
          git push --tags

