name: Deploy to prod
on: push
concurrency:
  group: "actiontests-prod"
jobs:
  tag:
    name: Tag the release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Get Message'
        id: 'changelog-ci'
        run: |
          echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
          echo "$(git log --oneline)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          
      - name: Get Changelog Output
        run: |
          echo "${{ steps.changelog-ci.outputs.commit_message }}"
          echo "${{ steps.changelog-ci.outputs.commit_message }}" >> $GITHUB_STEP_SUMMARY

          
      
  # slack:
  #   runs-on: ubuntu-latest
  #   if: ${{ always() }}
  #   needs:
  #     - deploy-prod-live
  #   steps:
  #     - uses: actions/checkout@v2
  #     - id: notify
  #       uses: privacy-com/shared-github-actions/.github/actions/slack@main
  #       with:
  #         SERVICE: privacy-dashboard
  #         ENVIRONMENT: production
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_PROD }}
  #         COLOR: ${{(!contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')) && '#00FF00' || '#FF0000' }}
