name: Deploy to prod
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag the build'
        required: true
        type: string
concurrency:
  group: "actiontests-prod"
jobs:
  prepare-release-log:
    name: Generate commit messages since last tagged release
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate commit messages since last tagged commit
        run: |
          promotedImageCommitHash=3c24d9c65ba99917d56411e0be84f06d3f5743a4
          echo $(git log --pretty=format:"%h%x09%an%x09%s" 408264b24edae4bb3c24eaa73f7fcd3968981bfa..$promotedImageCommitHash) >> $GITHUB_STEP_SUMMARY
